version: "3.8"

services:
  server:
    restart: always
    image: server
    container_name: server
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    restart: always
    image: postgresql
    container_name: db
    volumes:
      - data:/data/db
    ports:
      - "5432:5432"
    env_file:
      - ./.env


volumes:
  data: